#!/bin/bash
echo 'build this ..........'

buildpath='/home/$USER/code/build/tat/release'
mkdir -p ${buildpath}
cd ${buildpath} 
qmake /home/$USER/code/tat/src/tat.pro -r -spec linux-g++-64
echo 'makefile..........finished'

make -j8 -s 
echo 'building..........finished'

