#!/bin/bash
echo 'build this ..........'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

chmod u+w ~

buildpath="${DIR}/build/release"
mkdir -p ${buildpath}
cd ${buildpath} 
qmake ${DIR}/src/tat.pro -r -spec linux-g++-64
echo 'makefile..........finished'

threads="$(nproc)"    


make -j${threads} -s

echo 'building..........finished'



