#!/bin/bash
echo 'build this shit..........'

qmake tat.pro -r -spec linux-g++-64
echo 'makefile..........finished'

make -j8 -s 
echo 'building..........finished'


if [ -e config.xml ]
then
  echo 'config.xml........exists'
else
  ln -s ~/code/tat/bin/config.xml config.xml
  echo 'symlink to bin/config.xml'
fi

./tat
#cleanup
#rm Makefile
