#-------------------------------------------------
#
# Project created by QtCreator 2015-09-26T15:29:59
#
#-------------------------------------------------

QT       -= core gui

TARGET = tat-library
TEMPLATE = lib
CONFIG += object_parallel_to_source

DEFINES += TATLIBRARY_LIBRARY

QMAKE_CXXFLAGS += -std=c++14
QMAKE_CXXFLAGS += -march=native
QMAKE_CXXFLAGS += -stdlib=libc++

unix {
    target.path = /usr/lib
    INSTALLS += target
}

QMAKE_CXXFLAGS += -isystem /usr/local/include
QMAKE_CXXFLAGS += -isystem /usr/local/Cellar/boost/1.58.0/include

unix|win32: LIBS += -L/usr/local/Cellar/boost/1.58.0/lib -lboost_program_options
unix|win32: LIBS += -L/usr/local/Cellar/boost/1.58.0/lib -lboost_filesystem
unix|win32: LIBS += -L/usr/local/Cellar/boost/1.58.0/lib -lboost_system

HEADERS += \
    algorithm/stream/eof.h \
    algorithm/stream/getline.h \
    algorithm/stream/is_open.h \
    algorithm/stream/resetInputBeginning.h \
    algorithm/stream/validateOpenStream.h \
    algorithm/string/split.h \
    algorithm/string/starts_with.h \
    algorithm/string/trim.h \
    algorithm/string/trim_all.h \
    algorithm/valarray/valarray_to_vector.h \
    algorithm/valarray/vector_to_valarray.h \
    algorithm/vector/add.h \
    algorithm/vector/doubleToQuantity.h \
    algorithm/vector/doubleToString.h \
    algorithm/vector/fill_with_list_values_as_constructor_arg.h \
    algorithm/vector/find_all.h \
    algorithm/vector/ifzero.h \
    algorithm/vector/operator_overloads.h \
    algorithm/vector/quantityTodouble.h \
    algorithm/vector/ratio.h \
    algorithm/vector/repeatElements.h \
    algorithm/vector/reserve.h \
    algorithm/vector/split_vector_of_pairs.h \
    algorithm/vector/stdVector2ublasVector.h \
    algorithm/vector/stringToDouble.h \
    algorithm/vector/stringToQuantity.h \
    algorithm/vector/subtract.h \
    algorithm/vector/sum.h \
    algorithm/vector/vector2cstringArray.h \
    algorithm/algorithm.h \
    cout/vector/print.h \
    electronics/filter/low-pass/RC-first-order/phase_shift_from_input.hpp \
    electronics/filter/low-pass/RC-first-order/phase_shifts_from_input.hpp \
    filesystem/path.h \
    gTBC/gMeasure/gTBD/extract_frequency.h \
    gTBC/gMeasure/find_all_files_with.h \
    gTBC/gMeasure/find_unique_frequencies_in_files.h \
    gTBC/gMeasure/find_unique_labels_in_files.h \
    gTBC/gMeasure/find_unique_lambdas_in_files.h \
    gTBC/gMeasure/find_unique_measurements.h \
    gTBC/gMeasure/get_pair_measurements_at_frequency.h \
    gTBC/gMeasure/get_signal_from_scope_file.h \
    gTBC/gMeasure/import_sweep_meta_data.h \
    gTBC/gMeasure/import_twoColor_scope_files.h \
    gTBC/gMeasure/is_scope_file.h \
    gTBC/gMeasure/read_scope_file.h \
    gTBC/gMeasure/remove_grnd_if_not_in_scope_files.h \
    gTBC/gMeasure/scopeFile.h \
    gTBC/gMeasure/scopeFiles_from_datafiles.h \
    gTBC/gMeasure/total_calibrated_emission_pairs.h \
    gTBC/gMeasure/unique_measurement_pair.h \
    gTBC/gMeasure/Unique_scope_measurement.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/adiabatic_rear/aluminum_target/sept24/fit_a_b1_b2_RC.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/adiabatic_rear/aluminum_target/sept24/fit_models.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/adiabatic_rear/aluminum_target/sept24/run1_rear_70degC.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/heated_stage/sept23/fit_a_b1_b2_RC.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/heated_stage/sept23/fit_models.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/heated_stage/sept23/specimenE.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/heated_stage/sept23/specimenE_low_laser.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/heated_stage/sept23/specimenE_low_laser_high_stage.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/sept22/fit_a_b1_b2_RC.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/sept22/fit_models.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/sept22/specimenE.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/sept4/fit_a_b1_b2_RC.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/sept4/fit_a_b1_RC.h \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/sept4/fit_a_b2_RC.hpp \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/sept4/fit_models.hpp \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/sept4/specimenB.hpp \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/sept4/specimenE.hpp \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/sept4/specimenF.hpp \
    investigations/bulkDiffusivityMeasurements2015/beamExpander/sept4/specimenH.hpp \
    investigations/bulkDiffusivityMeasurements2015/run.hpp \
    investigations/twoColorPyrometery/calculators/steady_state_temperature.hpp \
    investigations/twoColorPyrometery/oneLayer2D/amplitude_analysis/amplitudes_from_experiment.h \
    investigations/twoColorPyrometery/oneLayer2D/calculators/thermal_penetration/lthermal_at_frequency.hpp \
    investigations/twoColorPyrometery/oneLayer2D/complex_temperature_check/complex_temperature_check.h \
    investigations/twoColorPyrometery/oneLayer2D/frequency_sweep/avg_phases_at_surface.h \
    investigations/twoColorPyrometery/oneLayer2D/frequency_sweep/surface_phases_at_radial_position.h \
    investigations/twoColorPyrometery/oneLayer2D/frequency_sweep/surface_phases_with_beam_diameter.h \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_a_b1_b2_b3/fit_all/fit.hpp \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_a_b1_b2_RC/fit_all/fit.hpp \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_a_offset/fit_all/fit.h \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_all/diffusivity_from_phases.h \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_all_but_detectorRadius/diffusivity_from_phases.h \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_all_but_diffusivity/diffusivity_from_phases.h \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_all_but_laser/diffusivity_from_phases.h \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/uncertainty_analysis.h \
    investigations/twoColorPyrometery/oneLayer2D/radial_temperature_gradient/surface_non_dimensional.hpp \
    investigations/twoColorPyrometery/oneLayer2D/temp_sweep/surface_radial_profile.h \
    investigations/twoColorPyrometery/plot/normalized_SR_exp_model.h \
    investigations/twoColorPyrometery/plot/phase_exp_model.h \
    investigations/twoColorPyrometery/plot/steady_surface_temperature.h \
    investigations/twoColorPyrometery/plot/transient_surface_amplitudes.h \
    investigations/twoColorPyrometery/plot/wave_signals.h \
    investigations/twoColorPyrometery/calculateCalibrationCoefficients.h \
    investigations/twoColorPyrometery/phase_fitting.h \
    investigations/twoColorPyrometery/temperature_prediction.h \
    investigations/execute.h \
    investigations/main-app.h \
    investigations/num_method2014.h \
    investigations/sensitivityvaldes2013.hpp \
    investigations/taylor_uncertainty.h \
    investigations/twoColorPyrometery.h \
    math/algorithms/combinations.hpp \
    math/algorithms/complex.h \
    math/algorithms/spline-quantity.h \
    math/algorithms/spline.h \
    math/algorithms/spline_cplx.h \
    math/calculus/mean_value/circle/circle.h \
    math/calculus/mean_value/circle/circle_complex.h \
    math/calculus/mean_value/function/function.h \
    math/calculus/mean_value/offset_circle/offset_circle.h \
    math/calculus/weighted_mean_value/circle.h \
    math/complex/adjust_phase.h \
    math/complex/adjust_phases.h \
    math/complex/extract_amplitudes_from_properties.h \
    math/complex/extract_phases_from_properties.h \
    math/complex/properties.h \
    math/construct/periodic_time_distribution.h \
    math/construct/range.h \
    math/coordinate_system/wrap_to_0_2Pi.h \
    math/coordinate_system/wrap_to_negPi_posPi.h \
    math/curveFit/cosine.h \
    math/curveFit/get_initial_conditions.h \
    math/differential/waveEquation/analytical.h \
    math/differential/waveEquation/two_layer_system.h \
    math/estimation/constrained.hpp \
    math/estimation/cosfit.hpp \
    math/estimation/lmdiff.hpp \
    math/estimation/parameterestimation.hpp \
    math/estimation/settings.h \
    math/estimation/utils.hpp \
    math/functions/trigonometric/coth.h \
    math/functions/trigonometric/csc.h \
    math/functions/trigonometric/csch.h \
    math/functions/trigonometric/sec.h \
    math/functions/cosine.h \
    math/functions/periodic.h \
    math/functions/periodicData.h \
    math/functions/PeriodicProperties.h \
    math/functions/sine.h \
    math/functions/wrap2pi.h \
    math/geometry/intersect/two_circles/angles_of_intersection.h \
    math/geometry/intersect/two_circles/if_intersect.h \
    math/geometry/intersect/two_circles/points_of_intersection.h \
    math/geometry/point/point.h \
    math/geometry/circle.h \
    math/geometry/interval.h \
    math/matrixAnalysis/valid.h \
    math/numericalAnalysis/differentiation/firstDerivative/central_difference.h \
    math/numericalAnalysis/differentiation/firstDerivative/forward_difference.h \
    math/numericalAnalysis/matrixs/inversion.h \
    math/numericalAnalysis/ublas/apply_to_all.h \
    math/numIntegration/gslfunc.hpp \
    math/numIntegration/integrate.h \
    math/numIntegration/simpsons_3_8.hpp \
    math/random/random.h \
    math/solvers/sor.h \
    math/solvers/tma.h \
    math/special_functions/bessel_j/J0.h \
    math/special_functions/bessel_j/J1.h \
    math/special_functions/bessel.h \
    math/transform/inverseHankel.h \
    math/utilities/equalto.h \
    math/utilities/even.h \
    math/bisection.hpp \
    math/utility.hpp \
    physics/classical_mechanics/kinematics.h \
    plot/gnuplot-iostream.h \
    plot/gnuplot.h \
    sensible/layer.h \
    sensible/property.h \
    sensible/radiativeSysProp.h \
    sensible/TBCsystem.h \
    sensible/temperature_scale.h \
    statistics/signal_processing/corrected_sample/standard_deviation.h \
    statistics/signal_processing/corrected_sample/variance.h \
    statistics/signal_processing/residuals/residual.h \
    statistics/signal_processing/residuals/residual_square.h \
    statistics/signal_processing/standard_deviation/sample.h \
    statistics/signal_processing/variance/sample_variance.h \
    statistics/signal_processing/average.h \
    statistics/signal_processing/divide_each_element.h \
    statistics/signal_processing/residuals_square.h \
    statistics/signal_processing/signal_to_noise.h \
    statistics/signal_processing/sum.h \
    statistics/signal_processing/sum_residuals_square.h \
    statistics/sum_of_squares/residuals.h \
    statistics/sum_of_squares/total.h \
    statistics/uncertainty_analysis/goodness_of_fit/goodness_of_fit.h \
    statistics/coefficient_of_determination.h \
    thermal/analysis/bulkSpeciman/temperature/conductivity_from_phases.h \
    thermal/analysis/cmplx_combination/cmplx_combination.h \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_a_b1_b2_RC/fit_all/fit.hpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_a_b1_RC/fit_all/fit.hpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_a_b2_RC/fit_all/fit.hpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_a_b3_RC/fit_all/fit.hpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_all/diffusivity_from_phases.h \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_all_but_detectorRadius/diffusivity_from_phases.h \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_all_but_diffusivity/diffusivity_from_phases.h \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_all_but_laser/diffusivity_from_phases.h \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_diffusivity_offset/fit_all/fit.h \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_diffusivity_offset_view_radius_beam/fit_all/fit.hpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/Best_fit.h \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/uncertainty_analysis.h \
    thermal/analysis/sweep/temp_cmplx.h \
    thermal/analysis/sweep/temp_ss.h \
    thermal/analysis/tbc2009/detector_offset/estimate_parameters/from_phases/from_phases.h \
    thermal/analysis/tbc2009/estimate_parameters/from_phases.h \
    thermal/analysis/two_layer_speciman/diffusivity_from_phases.h \
    thermal/analysis/basedata.hpp \
    thermal/analysis/gum_uncertainty.h \
    thermal/analysis/kernal.hpp \
    thermal/analysis/lmdiff_poptea.hpp \
    thermal/analysis/lmdiff_poptea_help.hpp \
    thermal/analysis/methods.hpp \
    thermal/analysis/pie.hpp \
    thermal/analysis/poptea.hpp \
    thermal/analysis/poptea_initialize.h \
    thermal/analysis/thermalData.hpp \
    thermal/analysis/thermalsweepoptimizer.hpp \
    thermal/define/conductivity.h \
    thermal/define/construct.hpp \
    thermal/define/diffusivity.h \
    thermal/define/effusivity.hpp \
    thermal/define/lthermal.h \
    thermal/define/model.hpp \
    thermal/define/model_type.h \
    thermal/define/omega.h \
    thermal/define/temperature.h \
    thermal/define/volumetricHeatCapacity.h \
    thermal/emission/blackBody/constants.h \
    thermal/emission/blackBody/planckWienApprox.h \
    thermal/emission/blackBody/signal.h \
    thermal/emission/planks_law/planks_law.h \
    thermal/emission/emission.hpp \
    thermal/emission/noise.hpp \
    thermal/emission/phase99.hpp \
    thermal/emission/signal.h \
    thermal/emission/signalRatio.h \
    thermal/emission/spectrum.h \
    thermal/equipment/detector/simulate_measurements/periodic_cosine.h \
    thermal/equipment/detector/spot_view/spot_view.h \
    thermal/equipment/detector/compensate_for_phase_difference.h \
    thermal/equipment/detector/detector.h \
    thermal/equipment/detector/fitted_measurements.h \
    thermal/equipment/detector/measurement.h \
    thermal/equipment/detector/measurements.h \
    thermal/equipment/laser.h \
    thermal/equipment/setup.h \
    thermal/experimental/observations/slab/slab.hpp \
    thermal/experimental/slab_with_observations/slab_with_observations.hpp \
    thermal/model/dimensionless/angular_frequency.h \
    thermal/model/dimensionless/length.h \
    thermal/model/dimensionless/temperature.h \
    thermal/model/dimensionless/time_nd.h \
    thermal/model/one_dim/analytical_2005/analytical_2005.h \
    thermal/model/one_dim/numerical_2011/mesh.hpp \
    thermal/model/one_dim/numerical_2011/numerical_2011.h \
    thermal/model/one_dim/numerical_2011/Numerical_Setup.h \
    thermal/model/one_dim/numerical_2011/Numerical_Temperature.h \
    thermal/model/one_dim/one_dim.h \
    thermal/model/one_dim/Tss_ana.h \
    thermal/model/oneLayer2D/complex/h.h \
    thermal/model/oneLayer2D/complex/h_surface.h \
    thermal/model/oneLayer2D/complex/kappa.h \
    thermal/model/oneLayer2D/complex/phase_amplitude.h \
    thermal/model/oneLayer2D/complex/phases_amplitudes.h \
    thermal/model/oneLayer2D/complex/surface_phase_amplitude.h \
    thermal/model/oneLayer2D/complex/surface_phases_amplitudes.h \
    thermal/model/oneLayer2D/complex/temperature.h \
    thermal/model/oneLayer2D/complex/temperature_nd.h \
    thermal/model/oneLayer2D/dimensional/deltaT.h \
    thermal/model/oneLayer2D/dimensional/thermal_penetration.hpp \
    thermal/model/oneLayer2D/dimensionless/b.h \
    thermal/model/oneLayer2D/dimensionless/thermal_penetration.h \
    thermal/model/oneLayer2D/phase_amplitude/surface_frequency_profile.h \
    thermal/model/oneLayer2D/phase_amplitude/surface_radial_profile.h \
    thermal/model/oneLayer2D/thermal_emission/centered_point/frequency_sweep.hpp \
    thermal/model/oneLayer2D/thermal_emission/offset_detector/frequency_sweep.hpp \
    thermal/model/oneLayer2D/thermal_emission/offset_detector/offset_measurement.hpp \
    thermal/model/oneLayer2D/thermal_emission/offset_point/frequency_sweep.h \
    thermal/model/oneLayer2D/thermal_emission/fast_measurement.h \
    thermal/model/oneLayer2D/thermal_emission/frequency_sweep.h \
    thermal/model/oneLayer2D/thermal_emission/measurement.h \
    thermal/model/oneLayer2D/thermal_emission/point_measurement.h \
    thermal/model/slab/import_slab.h \
    thermal/model/slab/slab.h \
    thermal/model/tbc2009/complexT/nu/hat.h \
    thermal/model/tbc2009/complexT/nu/tilde.h \
    thermal/model/tbc2009/complexT/offset_detector/average_surface_phase_amplitude.h \
    thermal/model/tbc2009/complexT/radiosity/J0.h \
    thermal/model/tbc2009/complexT/radiosity/J1.h \
    thermal/model/tbc2009/complexT/radiosity/J2.h \
    thermal/model/tbc2009/complexT/average_surface_phase_amplitude.h \
    thermal/model/tbc2009/complexT/F_tilde.h \
    thermal/model/tbc2009/complexT/h_coat.h \
    thermal/model/tbc2009/complexT/h_sub.h \
    thermal/model/tbc2009/complexT/h_system.h \
    thermal/model/tbc2009/complexT/H_tilde.h \
    thermal/model/tbc2009/complexT/phase_amplitude.h \
    thermal/model/tbc2009/complexT/phases_amplitudes.h \
    thermal/model/tbc2009/complexT/surface_phase_amplitude.h \
    thermal/model/tbc2009/complexT/temperature.h \
    thermal/model/tbc2009/dimensionless/a.h \
    thermal/model/tbc2009/dimensionless/b.h \
    thermal/model/tbc2009/dimensionless/c.h \
    thermal/model/tbc2009/dimensionless/coating_diffusivity_from_a.h \
    thermal/model/tbc2009/dimensionless/coating_from_dimensionless.h \
    thermal/model/tbc2009/dimensionless/gamma.h \
    thermal/model/tbc2009/dimensionless/HeatingProperties.h \
    thermal/model/tbc2009/dimensionless/import_heating_properties.h \
    thermal/model/tbc2009/dimensionless/Lambda.h \
    thermal/model/tbc2009/dimensionless/temperature.h \
    thermal/model/tbc2009/dimensionless/thermal_penetration.h \
    thermal/model/tbc2009/dimensionless/ThermalProperties.h \
    thermal/model/tbc2009/offset_detector/average_surface_phases.h \
    thermal/model/tbc2009/offset_detector/surface_T_phases_amplitudes.h \
    thermal/model/tbc2009/average_surface_phases.h \
    thermal/model/tbc2009/average_surface_phases_amplitudes.h \
    thermal/model/two_dim/analytical_2009/heat2DAna.hpp \
    thermal/model/two_layer/complex/phase.h \
    thermal/model/two_layer/complex/surface_phase.h \
    thermal/model/two_layer/complex/surface_phases.h \
    thermal/model/two_layer/complex/surface_temperature.h \
    thermal/model/two_layer/complex/temperature.h \
    thermal/model/two_layer/dimensionless/a.h \
    thermal/model/two_layer/dimensionless/angular_frequency.h \
    thermal/model/two_layer/dimensionless/b.h \
    thermal/model/two_layer/dimensionless/Kappa.h \
    thermal/model/two_layer/dimensionless/length.h \
    thermal/model/two_layer/dimensionless/time_nd.h \
    thermal/model/utilities/heat_generation/Iheat.h \
    thermal/model/utilities/nondimensional/tau_0.h \
    thermal/model/labels.h \
    thermal/pyrometry/twoColor/periodic/analysis_from_properties.h \
    thermal/pyrometry/twoColor/periodic/analysis_from_properties_sweep.h \
    thermal/pyrometry/twoColor/periodic/results.h \
    thermal/pyrometry/twoColor/periodic/transient_analysis.h \
    thermal/pyrometry/twoColor/periodic/transient_analysis_sweep.h \
    thermal/pyrometry/twoColor/periodic/transient_analysis_sweep_results.h \
    thermal/pyrometry/twoColor/calibrate_wavelength.h \
    thermal/pyrometry/twoColor/calibrate_wavelengths.h \
    thermal/pyrometry/twoColor/calibratedSignalRatio.h \
    thermal/pyrometry/twoColor/calibrationCoefficient.h \
    thermal/pyrometry/twoColor/calibrationGenerator.h \
    thermal/pyrometry/twoColor/normalizedDetectorMeasurements.h \
    thermal/pyrometry/twoColor/normalizedSignalRatio.h \
    thermal/pyrometry/twoColor/normalizedSignalRatio_from_measurement.h \
    thermal/pyrometry/twoColor/pyrometery_settings_file.h \
    thermal/pyrometry/twoColor/signalRatio.h \
    thermal/pyrometry/twoColor/temperatureSteady.h \
    thermal/simulations/Numerical_PhaseOfEmission.h \
    thermalfluids/dimensionless/prandtl_number.h \
    tools/bimap/bimap.h \
    tools/interface/import/columnData.h \
    tools/interface/exportfile.hpp \
    tools/interface/filesystem.hpp \
    tools/interface/xml.h \
    tools/programoptions/programoptions.hpp \
    tools/timing.h \
    tools/tools.hpp \
    units/cout/use_engineering_prefix.hpp \
    units/io/prefix.hpp \
    units/si/constants/codata.h \
    units/si/constants/thermal.h \
    units/si/extension.h \
    units/si/predefined.h \
    units/si/prefixes.h \
    units/si/si.h \
    units/si/si_literals.h \
    units/systems/si/base.h \
    units/cmath.h \
    units/conversions.h \
    units/operator_overloads.h \
    units/operators.h \
    units/physical_dimensions.h \
    units/quantity.h \
    units/scale.h \
    units/static_rational.h \
    units.h

SOURCES += \
    algorithm/stream/resetInputBeginning.cpp \
    algorithm/stream/validateOpenStream.cpp \
    algorithm/string/split.cpp \
    algorithm/string/starts_with.cpp \
    algorithm/vector/doubleToString.cpp \
    algorithm/vector/ifzero.cpp \
    algorithm/vector/stdVector2ublasVector.cpp \
    algorithm/vector/stringToDouble.cpp \
    electronics/filter/low-pass/RC-first-order/phase_shift_from_input.cpp \
    electronics/filter/low-pass/RC-first-order/phase_shifts_from_input.cpp \
    filesystem/path.cpp \
    gTBC/gMeasure/gTBD/extract_frequency.cpp \
    gTBC/gMeasure/find_all_files_with.cpp \
    gTBC/gMeasure/find_unique_frequencies_in_files.cpp \
    gTBC/gMeasure/find_unique_labels_in_files.cpp \
    gTBC/gMeasure/find_unique_lambdas_in_files.cpp \
    gTBC/gMeasure/find_unique_measurements.cpp \
    gTBC/gMeasure/get_pair_measurements_at_frequency.cpp \
    gTBC/gMeasure/get_signal_from_scope_file.cpp \
    gTBC/gMeasure/import_sweep_meta_data.cpp \
    gTBC/gMeasure/import_twoColor_scope_files.cpp \
    gTBC/gMeasure/is_scope_file.cpp \
    gTBC/gMeasure/read_scope_file.cpp \
    gTBC/gMeasure/remove_grnd_if_not_in_scope_files.cpp \
    gTBC/gMeasure/scopeFile.cpp \
    gTBC/gMeasure/scopeFiles_from_datafiles.cpp \
    gTBC/gMeasure/total_calibrated_emission_pairs.cpp \
    gTBC/gMeasure/unique_measurement_pair.cpp \
    gTBC/gMeasure/Unique_scope_measurement.cpp \
    investigations/bulkDiffusivityMeasurements2015/run.cpp \
    investigations/twoColorPyrometery/calculators/steady_state_temperature.cpp \
    investigations/twoColorPyrometery/oneLayer2D/amplitude_analysis/amplitudes_from_experiment.cpp \
    investigations/twoColorPyrometery/oneLayer2D/calculators/thermal_penetration/lthermal_at_frequency.cpp \
    investigations/twoColorPyrometery/oneLayer2D/complex_temperature_check/complex_temperature_check.cpp \
    investigations/twoColorPyrometery/oneLayer2D/frequency_sweep/avg_phases_at_surface.cpp \
    investigations/twoColorPyrometery/oneLayer2D/frequency_sweep/surface_phases_at_radial_position.cpp \
    investigations/twoColorPyrometery/oneLayer2D/frequency_sweep/surface_phases_with_beam_diameter.cpp \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_a_b1_b2_b3/fit_all/fit.cpp \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_a_b1_b2_RC/fit_all/fit.cpp \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_a_offset/fit_all/fit.cpp \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_all/diffusivity_from_phases.cpp \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_all_but_detectorRadius/diffusivity_from_phases.cpp \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_all_but_diffusivity/diffusivity_from_phases.cpp \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/fit_all_but_laser/diffusivity_from_phases.cpp \
    investigations/twoColorPyrometery/oneLayer2D/phase_analysis/uncertainty_analysis.cpp \
    investigations/twoColorPyrometery/oneLayer2D/radial_temperature_gradient/surface_non_dimensional.cpp \
    investigations/twoColorPyrometery/oneLayer2D/temp_sweep/surface_radial_profile.cpp \
    investigations/twoColorPyrometery/plot/normalized_SR_exp_model.cpp \
    investigations/twoColorPyrometery/plot/phase_exp_model.cpp \
    investigations/twoColorPyrometery/plot/steady_surface_temperature.cpp \
    investigations/twoColorPyrometery/plot/transient_surface_amplitudes.cpp \
    investigations/twoColorPyrometery/plot/wave_signals.cpp \
    investigations/twoColorPyrometery/calculateCalibrationCoefficients.cpp \
    investigations/twoColorPyrometery/phase_fitting.cpp \
    investigations/twoColorPyrometery/temperature_prediction.cpp \
    investigations/execute.cpp \
    investigations/main-app.cpp \
    investigations/num_method2014.cpp \
    investigations/sensitivityvaldes2013.cpp \
    investigations/taylor_uncertainty.cpp \
    investigations/twoColorPyrometery.cpp \
    math/algorithms/combinations.cpp \
    math/algorithms/complex.cpp \
    math/algorithms/spline.cpp \
    math/algorithms/spline_cplx.cpp \
    math/calculus/mean_value/circle/circle_complex.cpp \
    math/calculus/mean_value/offset_circle/offset_circle.cpp \
    math/calculus/weighted_mean_value/circle.cpp \
    math/construct/periodic_time_distribution.cpp \
    math/estimation/constrained.cpp \
    math/estimation/cosfit.cpp \
    math/estimation/lmdiff.cpp \
    math/estimation/parameterestimation.cpp \
    math/estimation/settings.cpp \
    math/estimation/utils.cpp \
    math/functions/trigonometric/coth.cpp \
    math/functions/trigonometric/csch.cpp \
    math/functions/wrap2pi.cpp \
    math/geometry/intersect/two_circles/angles_of_intersection.cpp \
    math/geometry/intersect/two_circles/if_intersect.cpp \
    math/geometry/intersect/two_circles/points_of_intersection.cpp \
    math/geometry/point/point.cpp \
    math/geometry/circle.cpp \
    math/geometry/interval.cpp \
    math/numIntegration/gslfunc.cpp \
    math/numIntegration/simpsons_3_8.cpp \
    math/random/random.cpp \
    math/solvers/sor.cpp \
    math/solvers/tma.cpp \
    math/transform/inverseHankel.cpp \
    math/bisection.cpp \
    math/utility.cpp \
    physics/classical_mechanics/kinematics.cpp \
    sensible/layer.cpp \
    sensible/property.cpp \
    sensible/radiativeSysProp.cpp \
    sensible/TBCsystem.cpp \
    sensible/temperature_scale.cpp \
    thermal/analysis/bulkSpeciman/temperature/conductivity_from_phases.cpp \
    thermal/analysis/cmplx_combination/cmplx_combination.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_a_b1_b2_RC/fit_all/fit.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_a_b1_RC/fit_all/fit.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_a_b2_RC/fit_all/fit.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_a_b3_RC/fit_all/fit.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_all/diffusivity_from_phases.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_all_but_detectorRadius/diffusivity_from_phases.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_all_but_diffusivity/diffusivity_from_phases.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_all_but_laser/diffusivity_from_phases.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_diffusivity_offset/fit_all/fit.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/fit_diffusivity_offset_view_radius_beam/fit_all/fit.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/Best_fit.cpp \
    thermal/analysis/oneLayer2D/estimate_parameters/phase_analysis/uncertainty_analysis.cpp \
    thermal/analysis/sweep/temp_cmplx.cpp \
    thermal/analysis/sweep/temp_ss.cpp \
    thermal/analysis/tbc2009/detector_offset/estimate_parameters/from_phases/from_phases.cpp \
    thermal/analysis/tbc2009/estimate_parameters/from_phases.cpp \
    thermal/analysis/two_layer_speciman/diffusivity_from_phases.cpp \
    thermal/analysis/gum_uncertainty.cpp \
    thermal/analysis/kernal.cpp \
    thermal/analysis/lmdiff_poptea.cpp \
    thermal/analysis/lmdiff_poptea_help.cpp \
    thermal/analysis/methods.cpp \
    thermal/analysis/pie.cpp \
    thermal/analysis/poptea.cpp \
    thermal/analysis/poptea_initialize.cpp \
    thermal/analysis/thermalData.cpp \
    thermal/analysis/thermalsweepoptimizer.cpp \
    thermal/define/conductivity.cpp \
    thermal/define/construct.cpp \
    thermal/define/diffusivity.cpp \
    thermal/define/effusivity.cpp \
    thermal/define/lthermal.cpp \
    thermal/define/model.cpp \
    thermal/define/omega.cpp \
    thermal/define/temperature.cpp \
    thermal/define/volumetricHeatCapacity.cpp \
    thermal/emission/blackBody/planckWienApprox.cpp \
    thermal/emission/planks_law/planks_law.cpp \
    thermal/emission/emission.cpp \
    thermal/emission/noise.cpp \
    thermal/emission/phase99.cpp \
    thermal/equipment/detector/simulate_measurements/periodic_cosine.cpp \
    thermal/equipment/detector/spot_view/spot_view.cpp \
    thermal/equipment/detector/compensate_for_phase_difference.cpp \
    thermal/equipment/detector/detector.cpp \
    thermal/equipment/detector/fitted_measurements.cpp \
    thermal/equipment/detector/measurement.cpp \
    thermal/equipment/detector/measurements.cpp \
    thermal/equipment/laser.cpp \
    thermal/equipment/setup.cpp \
    thermal/experimental/observations/slab/slab.cpp \
    thermal/experimental/slab_with_observations/slab_with_observations.cpp \
    thermal/model/dimensionless/angular_frequency.cpp \
    thermal/model/dimensionless/length.cpp \
    thermal/model/dimensionless/temperature.cpp \
    thermal/model/dimensionless/time_nd.cpp \
    thermal/model/one_dim/analytical_2005/analytical_2005.cpp \
    thermal/model/one_dim/numerical_2011/mesh.cpp \
    thermal/model/one_dim/numerical_2011/numerical_2011.cpp \
    thermal/model/one_dim/numerical_2011/Numerical_Setup.cpp \
    thermal/model/one_dim/numerical_2011/Numerical_Temperature.cpp \
    thermal/model/one_dim/one_dim.cpp \
    thermal/model/one_dim/Tss_ana.cpp \
    thermal/model/oneLayer2D/complex/h.cpp \
    thermal/model/oneLayer2D/complex/h_surface.cpp \
    thermal/model/oneLayer2D/complex/kappa.cpp \
    thermal/model/oneLayer2D/complex/phase_amplitude.cpp \
    thermal/model/oneLayer2D/complex/phases_amplitudes.cpp \
    thermal/model/oneLayer2D/complex/surface_phase_amplitude.cpp \
    thermal/model/oneLayer2D/complex/surface_phases_amplitudes.cpp \
    thermal/model/oneLayer2D/complex/temperature.cpp \
    thermal/model/oneLayer2D/complex/temperature_nd.cpp \
    thermal/model/oneLayer2D/dimensional/deltaT.cpp \
    thermal/model/oneLayer2D/dimensional/thermal_penetration.cpp \
    thermal/model/oneLayer2D/dimensionless/b.cpp \
    thermal/model/oneLayer2D/dimensionless/thermal_penetration.cpp \
    thermal/model/oneLayer2D/phase_amplitude/surface_frequency_profile.cpp \
    thermal/model/oneLayer2D/phase_amplitude/surface_radial_profile.cpp \
    thermal/model/oneLayer2D/thermal_emission/centered_point/frequency_sweep.cpp \
    thermal/model/oneLayer2D/thermal_emission/offset_detector/frequency_sweep.cpp \
    thermal/model/oneLayer2D/thermal_emission/offset_detector/offset_measurement.cpp \
    thermal/model/oneLayer2D/thermal_emission/offset_point/frequency_sweep.cpp \
    thermal/model/oneLayer2D/thermal_emission/fast_measurement.cpp \
    thermal/model/oneLayer2D/thermal_emission/frequency_sweep.cpp \
    thermal/model/oneLayer2D/thermal_emission/measurement.cpp \
    thermal/model/oneLayer2D/thermal_emission/point_measurement.cpp \
    thermal/model/slab/import_slab.cpp \
    thermal/model/slab/slab.cpp \
    thermal/model/tbc2009/complexT/nu/hat.cpp \
    thermal/model/tbc2009/complexT/nu/tilde.cpp \
    thermal/model/tbc2009/complexT/offset_detector/average_surface_phase_amplitude.cpp \
    thermal/model/tbc2009/complexT/radiosity/J0.cpp \
    thermal/model/tbc2009/complexT/radiosity/J1.cpp \
    thermal/model/tbc2009/complexT/radiosity/J2.cpp \
    thermal/model/tbc2009/complexT/average_surface_phase_amplitude.cpp \
    thermal/model/tbc2009/complexT/F_tilde.cpp \
    thermal/model/tbc2009/complexT/h_coat.cpp \
    thermal/model/tbc2009/complexT/h_sub.cpp \
    thermal/model/tbc2009/complexT/h_system.cpp \
    thermal/model/tbc2009/complexT/H_tilde.cpp \
    thermal/model/tbc2009/complexT/phase_amplitude.cpp \
    thermal/model/tbc2009/complexT/phases_amplitudes.cpp \
    thermal/model/tbc2009/complexT/surface_phase_amplitude.cpp \
    thermal/model/tbc2009/complexT/temperature.cpp \
    thermal/model/tbc2009/dimensionless/a.cpp \
    thermal/model/tbc2009/dimensionless/b.cpp \
    thermal/model/tbc2009/dimensionless/c.cpp \
    thermal/model/tbc2009/dimensionless/coating_diffusivity_from_a.cpp \
    thermal/model/tbc2009/dimensionless/coating_from_dimensionless.cpp \
    thermal/model/tbc2009/dimensionless/gamma.cpp \
    thermal/model/tbc2009/dimensionless/HeatingProperties.cpp \
    thermal/model/tbc2009/dimensionless/import_heating_properties.cpp \
    thermal/model/tbc2009/dimensionless/Lambda.cpp \
    thermal/model/tbc2009/dimensionless/temperature.cpp \
    thermal/model/tbc2009/dimensionless/thermal_penetration.cpp \
    thermal/model/tbc2009/dimensionless/ThermalProperties.cpp \
    thermal/model/tbc2009/offset_detector/average_surface_phases.cpp \
    thermal/model/tbc2009/offset_detector/surface_T_phases_amplitudes.cpp \
    thermal/model/tbc2009/average_surface_phases.cpp \
    thermal/model/tbc2009/average_surface_phases_amplitudes.cpp \
    thermal/model/two_dim/analytical_2009/heat2DAna.cpp \
    thermal/model/two_layer/complex/phase.cpp \
    thermal/model/two_layer/complex/surface_phase.cpp \
    thermal/model/two_layer/complex/surface_phases.cpp \
    thermal/model/two_layer/complex/surface_temperature.cpp \
    thermal/model/two_layer/complex/temperature.cpp \
    thermal/model/two_layer/dimensionless/a.cpp \
    thermal/model/two_layer/dimensionless/angular_frequency.cpp \
    thermal/model/two_layer/dimensionless/b.cpp \
    thermal/model/two_layer/dimensionless/Kappa.cpp \
    thermal/model/two_layer/dimensionless/length.cpp \
    thermal/model/two_layer/dimensionless/time_nd.cpp \
    thermal/model/utilities/heat_generation/Iheat.cpp \
    thermal/model/utilities/nondimensional/tau_0.cpp \
    thermal/model/labels.cpp \
    thermal/pyrometry/twoColor/periodic/analysis_from_properties.cpp \
    thermal/pyrometry/twoColor/periodic/analysis_from_properties_sweep.cpp \
    thermal/pyrometry/twoColor/periodic/results.cpp \
    thermal/pyrometry/twoColor/periodic/transient_analysis.cpp \
    thermal/pyrometry/twoColor/periodic/transient_analysis_sweep.cpp \
    thermal/pyrometry/twoColor/periodic/transient_analysis_sweep_results.cpp \
    thermal/pyrometry/twoColor/calibrate_wavelength.cpp \
    thermal/pyrometry/twoColor/calibrate_wavelengths.cpp \
    thermal/pyrometry/twoColor/calibratedSignalRatio.cpp \
    thermal/pyrometry/twoColor/normalizedDetectorMeasurements.cpp \
    thermal/pyrometry/twoColor/normalizedSignalRatio.cpp \
    thermal/pyrometry/twoColor/normalizedSignalRatio_from_measurement.cpp \
    thermal/pyrometry/twoColor/pyrometery_settings_file.cpp \
    thermal/pyrometry/twoColor/signalRatio.cpp \
    thermal/pyrometry/twoColor/temperatureSteady.cpp \
    thermal/simulations/Numerical_PhaseOfEmission.cpp \
    tools/interface/import/columnData.cpp \
    tools/interface/exportfile.cpp \
    tools/interface/filesystem.cpp \
    tools/interface/xml.cpp \
    tools/programoptions/programoptions.cpp \
    tools/timing.cpp \
    units/cout/use_engineering_prefix.cpp

